language: php

php:
  - 7.0

# Elasticsearch 5 requires Java 8
addons:
  apt:
    packages:
      - oracle-java8-set-default

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle

install:
  - java -version
  - wget http://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.tar.gz
  - tar -xvf elasticsearch-5.1.1.tar.gz
  - export PATH=${PWD}/elasticsearch-5.1.1/bin/:${PATH}
  - elasticsearch --version

before_script:
  - elasticsearch > temp.txt &
  - sleep 10
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit